
# Project settings
# =================

## Development server
HOST: 0.0.0.0
PORT: 8080

## Ignore the views listed here when generating the static files
VIEWS_IGNORE:
  - html/base.html
  - html/index.html
  - html/post.html

## Ignore the views listed here in the _index
VIEWS_LIST_IGNORE:
  - html/base.html
  - html/index.html
  - html/post.html

## Enabled pre-processors
PRE_PROCESSORS: 
  - markdown

## Enabled post-processors
POST_PROCESSORS: 
  - pygments

LAYOUTS: html

## Constants
GITHUB_URL: https://github.com/lucuma/moar
GOOGLE_ANALYTICS_CODE: UA-1495972-14
