
# Project settings
# =================

## Development server
host: 0.0.0.0
port: 8080

## Ignore the views listed here when generating the static files
views_ignore:
  - html/base.html
  - html/index.html
  - html/post.html

## Ignore the views listed here in the _index
views_list_ignore:
  - html/base.html
  - html/index.html
  - html/post.html

## Enabled pre-processors
pre_processors: 
  - markdown

## Enabled post-processors
post_processors: 
  - pygments

theme_prefix: html

## Constants
github_url: https://github.com/lucuma/moar
google_analytics_code: UA-1495972-14
